-- Xóa tất cả tables cũ (nếu có)
DROP TABLE IF EXISTS public.notification_reads CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.fee_records CASCADE;
DROP TABLE IF EXISTS public.fee_types CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.student_parent CASCADE;
DROP TABLE IF EXISTS public.parents CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.grades CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.school_settings CASCADE;

-- Xóa functions cũ
DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.notify_absence() CASCADE;
DROP FUNCTION IF EXISTS public.has_role(text) CASCADE;

BEGIN;

-- ===============
-- 1) Core tables
-- ===============

-- Users profile
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  email text,
  phone text,
  role text NOT NULL DEFAULT 'Parent' CHECK (role IN ('Admin','Teacher','Accountant','Parent')),
  teacher_code text UNIQUE,
  avatar text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Grades
CREATE TABLE IF NOT EXISTS public.grades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE CHECK (name IN ('Mầm','Chồi','Lá')),
  sort_order int NOT NULL DEFAULT 0,
  description text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Classes
CREATE TABLE IF NOT EXISTS public.classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_code text UNIQUE,
  grade_id bigint REFERENCES public.grades(id) ON DELETE SET NULL,
  name text NOT NULL,
  teacher_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  room text,
  max_students int NOT NULL DEFAULT 30,
  description text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (room, name)
);

-- Students
CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  student_code text NOT NULL UNIQUE,
  full_name text NOT NULL,
  date_of_birth date,
  gender text CHECK (gender IN ('Male','Female')),
  ethnicity text,
  nationality text DEFAULT 'Việt Nam',
  address text,
  enrolled_date date,
  health_info jsonb NOT NULL DEFAULT '{}',
  avatar text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Parents
CREATE TABLE IF NOT EXISTS public.parents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  full_name text NOT NULL,
  phone text NOT NULL,
  email text,
  relationship text NOT NULL DEFAULT 'Guardian' CHECK (relationship IN ('Father','Mother','Guardian')),
  occupation text,
  address text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Student-Parent link
CREATE TABLE IF NOT EXISTS public.student_parent (
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  parent_id uuid NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
  relation_type text NOT NULL DEFAULT 'Guardian',
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (student_id, parent_id),
  UNIQUE (student_id, parent_id)
);

-- Attendance (CHÚ Ý: dùng `attendance_date` không phải `date`)
CREATE TABLE IF NOT EXISTS public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  attendance_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('present','absent','late')),
  check_in_time time,
  check_out_time time,
  note text,
  created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (student_id, attendance_date)
);

-- Fee types
CREATE TABLE IF NOT EXISTS public.fee_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  amount_vnd numeric(12,0) NOT NULL CHECK (amount_vnd > 0),
  grade_id bigint REFERENCES public.grades(id) ON DELETE SET NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Fee records
CREATE TABLE IF NOT EXISTS public.fee_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  fee_type_id bigint NOT NULL REFERENCES public.fee_types(id) ON DELETE RESTRICT,
  school_year text NOT NULL,
  month int CHECK (month >= 1 AND month <= 12),
  amount_vnd numeric(12,0) NOT NULL CHECK (amount_vnd > 0),
  paid_amount_vnd numeric(12,0) NOT NULL DEFAULT 0 CHECK (paid_amount_vnd >= 0),
  paid_date date,
  due_date date,
  payment_method text CHECK (payment_method IN ('cash','bank_transfer')),
  status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid','partial','paid')),
  created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (student_id, fee_type_id, school_year, month)
);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_parent_id uuid REFERENCES public.parents(id) ON DELETE CASCADE,
  recipient_user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL,
  kind text NOT NULL DEFAULT 'general' CHECK (kind IN ('general','event','holiday','request','absence')),
  target_type text DEFAULT 'specific',
  student_id uuid REFERENCES public.students(id) ON DELETE SET NULL,
  attendance_id uuid REFERENCES public.attendance(id) ON DELETE SET NULL,
  sent_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Notification reads
CREATE TABLE IF NOT EXISTS public.notification_reads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  parent_id uuid REFERENCES public.parents(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (notification_id, parent_id, user_id)
);

-- School settings
CREATE TABLE IF NOT EXISTS public.school_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_name text NOT NULL,
  address text,
  phone text,
  email text,
  school_year text NOT NULL,
  academic_year_start date,
  academic_year_end date,
  logo_url text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (school_year)
);

-- ==================
-- 2) Indexes
-- ==================
CREATE INDEX IF NOT EXISTS idx_students_class_id ON public.students(class_id);
CREATE INDEX IF NOT EXISTS idx_students_student_code ON public.students(student_code);
CREATE INDEX IF NOT EXISTS idx_users_teacher_code ON public.users(teacher_code);
CREATE INDEX IF NOT EXISTS idx_classes_class_code ON public.classes(class_code);
CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON public.attendance(student_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_class_date ON public.attendance(class_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_fee_records_student ON public.fee_records(student_id);
CREATE INDEX IF NOT EXISTS idx_classes_grade_id ON public.classes(grade_id);
CREATE INDEX IF NOT EXISTS idx_student_parent_parent_id ON public.student_parent(parent_id);
CREATE INDEX IF NOT EXISTS idx_parents_user_id ON public.parents(user_id);

-- ==================
-- 3) Triggers
-- ==================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','grades','classes','students','parents','attendance','fee_types','fee_records','notifications','school_settings']
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_set_updated_at' AND tgrelid = t::regclass) THEN
      EXECUTE FORMAT('CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()', t);
    END IF;
  END LOOP;
END;
$$;

-- Auto-create user on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, full_name, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', SPLIT_PART(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'phone',
    COALESCE(NEW.raw_user_meta_data->>'role', 'Parent')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==================
-- 4) RLS
-- ==================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_parent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_settings ENABLE ROW LEVEL SECURITY;

-- Helper function
CREATE OR REPLACE FUNCTION public.has_role(role_name text)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = role_name);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Policies
CREATE POLICY "Users can view all" ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can update self" ON public.users FOR UPDATE TO authenticated USING (id = auth.uid());
CREATE POLICY "Admin manages users" ON public.users FOR ALL TO authenticated USING (public.has_role('Admin'));

CREATE POLICY "Everyone reads grades" ON public.grades FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admin manages grades" ON public.grades FOR ALL TO authenticated USING (public.has_role('Admin'));

CREATE POLICY "Staff reads classes" ON public.classes FOR SELECT TO authenticated USING (public.has_role('Admin') OR public.has_role('Teacher') OR public.has_role('Accountant'));
CREATE POLICY "Admin manages classes" ON public.classes FOR ALL TO authenticated USING (public.has_role('Admin'));
CREATE POLICY "Teacher manages classes" ON public.classes FOR ALL TO authenticated USING (public.has_role('Teacher'));

CREATE POLICY "Staff reads students" ON public.students FOR SELECT TO authenticated USING (public.has_role('Admin') OR public.has_role('Teacher') OR public.has_role('Accountant'));
CREATE POLICY "Admin manages students" ON public.students FOR ALL TO authenticated USING (public.has_role('Admin'));
CREATE POLICY "Teacher manages students" ON public.students FOR ALL TO authenticated USING (public.has_role('Teacher'));

CREATE POLICY "Admin manages parents" ON public.parents FOR ALL TO authenticated USING (public.has_role('Admin'));
CREATE POLICY "Parent reads self" ON public.parents FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admin manages student_parent" ON public.student_parent FOR ALL TO authenticated USING (public.has_role('Admin'));
CREATE POLICY "Teacher manages student_parent" ON public.student_parent FOR ALL TO authenticated USING (public.has_role('Teacher'));

CREATE POLICY "Staff manages attendance" ON public.attendance FOR ALL TO authenticated USING (public.has_role('Admin') OR public.has_role('Teacher'));

CREATE POLICY "Staff reads fee_types" ON public.fee_types FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admin manages fee_types" ON public.fee_types FOR ALL TO authenticated USING (public.has_role('Admin'));

CREATE POLICY "Staff manages fee_records" ON public.fee_records FOR ALL TO authenticated USING (public.has_role('Admin') OR public.has_role('Accountant'));

CREATE POLICY "Admin manages notifications" ON public.notifications FOR ALL TO authenticated USING (public.has_role('Admin'));
CREATE POLICY "Parent reads own notifications" ON public.notifications FOR SELECT TO authenticated USING (recipient_user_id = auth.uid());

CREATE POLICY "Parent manages own reads" ON public.notification_reads FOR ALL TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Staff reads settings" ON public.school_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admin manages settings" ON public.school_settings FOR ALL TO authenticated USING (public.has_role('Admin'));

-- ==================
-- 5) Grants
-- ==================
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, UPDATE, DELETE ON public.users TO authenticated;
GRANT SELECT ON public.grades TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.classes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.students TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.parents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.student_parent TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.attendance TO authenticated;
GRANT SELECT ON public.fee_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fee_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fee_records TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notification_reads TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.school_settings TO authenticated;

-- ==================
-- 6) Sample Data
-- ==================
INSERT INTO public.grades (name, sort_order, description) VALUES
('Mầm', 1, 'Nhóm trẻ 3-4 tuổi'),
('Chồi', 2, 'Nhóm trẻ 4-5 tuổi'),
('Lá', 3, 'Nhóm trẻ 5-6 tuổi');

INSERT INTO public.classes (grade_id, name, room, max_students) VALUES
(1, 'Mầm 1', 'P101', 25),
(1, 'Mầm 2', 'P102', 25),
(2, 'Chồi 1', 'P201', 25),
(2, 'Chồi 2', 'P202', 25),
(3, 'Lá 1', 'P301', 25),
(3, 'Lá 2', 'P302', 25);

INSERT INTO public.fee_types (name, amount_vnd, description) VALUES
('Học phí Mầm', 3500000, 'Học phí tháng cho khối Mầm'),
('Học phí Chồi', 4000000, 'Học phí tháng cho khối Chồi'),
('Học phí Lá', 4500000, 'Học phí tháng cho khối Lá'),
('Bảo hiểm', 500000, 'Bảo hiểm tai nạn năm học'),
('Ăn trưa', 1500000, 'Tiền ăn trưa tháng'),
('Đồng phục', 800000, 'Bộ đồng phục');

INSERT INTO public.school_settings (school_name, address, phone, email, school_year) VALUES
('Trường Mầm Non KidGarden', '123 Đường Nguyễn Huệ, Quận 1, TP.HCM', '028 1234 5678', 'kidgarden@example.com', '2024-2025');

INSERT INTO public.students (class_id, student_code, full_name, date_of_birth, gender, address) VALUES
(1, 'KG-2024-0001', 'Nguyễn Minh Tuấn', '2021-03-15', 'Male', '123 Đường A, Quận 1'),
(1, 'KG-2024-0002', 'Trần Thị Lan', '2021-05-22', 'Female', '456 Đường B, Quận 2'),
(1, 'KG-2024-0003', 'Lê Văn Hùng', '2021-01-10', 'Male', '789 Đường C, Quận 3'),
(2, 'KG-2024-0004', 'Phạm Thị Hương', '2021-08-08', 'Female', '321 Đường D, Quận 4'),
(3, 'KG-2024-0005', 'Hoàng Văn Nam', '2020-04-20', 'Male', '654 Đường E, Quận 5'),
(3, 'KG-2024-0006', 'Vũ Thị Mai', '2020-12-25', 'Female', '987 Đường F, Quận 6'),
(4, 'KG-2024-0007', 'Đặng Minh Khoa', '2020-09-18', 'Male', '147 Đường G, Quận 7'),
(5, 'KG-2024-0008', 'Bùi Thị Thu', '2020-02-14', 'Female', '258 Đường H, Quận 8');

COMMIT;
